#
# Makefile for Pascal's Triangle
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
#

# You can set these variables from the command line.
PYTHON       = /usr/bin/python3.8


help:
	@echo "Please use \`make <target>' where <target> is one of"
	@echo "  run        will build Triangle with default line number (10)"
	@echo "  test       test the triangle generation"


run:
	$(PYTHON) pascal.py

unittest:
	$(PYTHON) -m unittest


